S3
iO-Academy/2024-may-invoicing-sloth-rockets pull request #15
Opened 2024-07-04 15:24 UTC by toonbie

2024-07-04 15:24 UTC, toonbie commented
If you close your eyes and imagine a happy client the story is perfect and needs no changes

2024-07-04 15:32 UTC, ashleycoles requested changes

2024-07-04 15:32 UTC, ashleycoles commented on src/component/ClientDropdown/index.jsx
> +function ClientDropdown({ clients, selectedClient, setSelectedClient, storeClient }) {
Are all of these props actually used?

2024-07-04 15:32 UTC, ashleycoles commented on src/component/CreateInvoice/index.jsx
> +        var newList = details.slice()
use let instead

2024-07-04 15:32 UTC, ashleycoles commented on src/component/InvoiceRow/index.jsx
> +        var newDetails = {
lettttttttttt

2024-07-04 15:32 UTC, ashleycoles commented on src/component/InvoiceRow/index.jsx
> +
empty line can go

2024-07-04 15:32 UTC, ashleycoles commented on src/component/Header/index.jsx
> +                <Link className="bg-cyan-500 px-3 py-2 rounded text-white " to="/CreateInvoice"><i className="bg-black rounded-md px-1 not-italic">+</i> New Invoice</Link>
remove the empty space at the end of the className

2024-07-04 15:32 UTC, ashleycoles commented on src/component/CreateInvoice/index.jsx
> +                <button className="bg-red-500 text-white p-2 rounded">Cancel invoice</button>
Does this do anything?

2024-07-04 15:32 UTC, ashleycoles commented on src/component/CreateInvoice/index.jsx
> +                {<p className="text-red-600 italic font-mono self-center animate-bounce">{errorMessage}</p>}
Why is this whole thing in {}?

2024-07-04 15:32 UTC, ashleycoles commented on src/component/CreateInvoice/index.jsx
> +            "total": details.reduce((carry, detail) => carry + detail.total, 0),
You're having to calculate the total twice, once here and once in the JSX. Can you find a way to only need this once?

2024-07-04 15:32 UTC, ashleycoles commented on src/component/CreateInvoice/index.jsx
> +    const [clients, setClients] = useState([{ id: "" }])
Why not just make this an empty array?

2024-07-04 15:45 UTC, toonbie commented on src/component/CreateInvoice/index.jsx
> +            "total": details.reduce((carry, detail) => carry + detail.total, 0),
No, I cannot ; function over beauty

2024-07-05 09:55 UTC, ashleycoles approved these changes

2024-07-05 09:55 UTC, merged